import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Dashboard } from "@/components/Amin-Components/Dashboard/Dashboard";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Layout({ children }) {
    const session = await auth();
    return (
        <SessionProvider session={session} supressFirstRenderFlash={true}>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <Dashboard session={session}>
                        {children}
                    </Dashboard>
                </body>
            </html>
        </SessionProvider>
    );
}
