import { Geist, Geist_Mono } from "next/font/google";

import { Dashboard } from "@/components/Admin-Components/Dashboard/Dashboard";
import { auth } from "@/auth";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Admin | Dashboard",
    description: "Generated by create next app",
};

export default async function Layout({ children }) {
    const session = await auth();
    return (
        <Dashboard session={session}>
            {children}
        </Dashboard>
    );
}