import {
    BadgeHelp,
    CircleHelp,
    Award,
    HeartHandshake,
    Handshake,
    Mail,
    Link,
    Star,
    Tag,
    Users,
    Shell,
    ArrowBigUpDash,
    CalendarSync,
    Download,
    Play,
    GraduationCap,
    TrendingUp,
    Speech,
    MessageCircleCode,
    Heart,
    Lightbulb,
    Brain,
    HandHeart,
    MessagesSquare,
    NotebookPen,
    Hourglass,
    CalendarDays,
    GroupIcon,
    Laptop,
    LaptopMinimal,
    Check,
    BadgeHelpIcon,
    Bell,
    BellDotIcon,
    Drama,
    ALargeSmall,
    Airplay,
    Amphora,
    AmphoraIcon,
    Armchair,
    AppWindowMac,
    AppWindow,
    AppWindowMacIcon,
    AtSign,
    Atom,
    AudioLines,
    AudioWaveform,
    Banana,
    BananaIcon,
    Blocks,
    Bolt,
    BookOpenText,
    BriefcaseBusiness,
    Camera,
    ChefHat,
    CircleUser,
    CircleUserRound,
    CircuitBoard,
    Clapperboard,
    Clock,
    Coffee,
    Command,
    ConciergeBell,
    Computer,
    Component,
    Contact,
    Contact2,
    ContactRound,
    Croissant,
    Ear,
    AlarmClockCheck,
    Flower,
    Flower2,
    Footprints,
    Gem,
    Gift,
    GlassWater,
    House,
    IdCard,
    Luggage,
    Martini,
    Phone,
    PersonStanding,
    PodcastIcon,
    Wine,
    Utensils,
    UtensilsCrossed,
    Podcast,
  } from 'lucide-react';
import { FaFacebook } from 'react-icons/fa';
  
  // Declare the icons object
  const icons = {
    BadgeHelp: <BadgeHelp  />,
    CircleHelp: <CircleHelp  />,
    Award: <Award  />,
    HeartHandshake: <HeartHandshake  />,
    Handshake: <Handshake  />,
    Mail: <Mail  />,
    Link: <Link  />,
    Drama:<Drama />,
    BadgeHelpIcon: <BadgeHelpIcon  />,
    Bell: <Bell  />,
    alargesmall:<ALargeSmall/>,
    airplay:<Airplay/>,
    alarmclockcheck:<AlarmClockCheck/>,
    amphora:<Amphora/>,
    amphoraIcon:<AmphoraIcon/>,
    armchair:<Armchair/>,
    appwindowmac:<AppWindowMac/>,
    appwindow:<AppWindow/>,
    appwindowmacIcon:<AppWindowMacIcon/>,
    BellDotIcon: <BellDotIcon  />,
    GroupIcon: <GroupIcon  />,
    Laptop: <Laptop  />,
    LaptopMinimal: <LaptopMinimal  />,
    Check: <Check  />,
    Star: <Star  />,
    Tag: <Tag  />,
    Users: <Users  />,
    Shell: <Shell  />,
    ArrowBigUpDash: <ArrowBigUpDash  />,
    CalendarSync: <CalendarSync  />,
    Download: <Download  />,
    Play: <Play  />,
    GraduationCap: <GraduationCap  />,
    TrendingUp: <TrendingUp  />,
    Speech: <Speech  />,
    MessageCircleCode: <MessageCircleCode  />,
    Heart: <Heart  />,
    Lightbulb: <Lightbulb  />,
    Brain: <Brain  />,
    HandHeart: <HandHeart  />,
    MessagesSquare: <MessagesSquare  />,
    NotebookPen: <NotebookPen  />,
    Hourglass: <Hourglass  />,
    CalendarDays: <CalendarDays  />,
    atsign:<AtSign/>,
    atom:<Atom/>,
    audioLINES:<AudioLines/>,
    audiowaveform:<AudioWaveform/>,
    banana:<Banana/>,
    bananaIcon:<BananaIcon/>,
    blocks:<Blocks/>,
    bolt:<Bolt/>,
    bookOpenText:<BookOpenText/>,
    briefcaseBusiness:<BriefcaseBusiness/>,
    brain:<Brain/>,
    camera:<Camera/>,
    chefhat:<ChefHat/>,
    circleuser:<CircleUser/>,
    circleuserround:<CircleUserRound/>,
    circuitboard:<CircuitBoard/>,
    clapperboard:<Clapperboard/>,
    clock:<Clock/>,
    coffee:<Coffee/>,
    command:<Command/>,
    conciergebell:<ConciergeBell/>,
    computer:<Computer/>,
    component:<Component/>,
    contact:<Contact/>,
    contact2:<Contact2/>,
    contactround:<ContactRound/>,
    croissant:<Croissant/>,
    ear:<Ear/>,
    facebook:<FaFacebook/>,
    flower2:<Flower2/>,
    footprints:<Footprints/>,
    gem:<Gem/>,
    gift:<Gift/>,
    glasswater:<GlassWater/>,
    house:<House/>,
    IdCard:<IdCard/>,
    luggage:<Luggage/>,
    martini:<Martini/>,
    phone:<Phone/>,
    personstanding:<PersonStanding/>,
    podcast:<Podcast/>,
    Wine:<Wine/>,
    Utensils:<Utensils/>,
    utensilsCrossed:<UtensilsCrossed/>



  };
  
  // Export the icons object as the default export
  export default icons;
  