import {
    BadgeHelp,
    CircleHelp,
    Award,
    HeartHandshake,
    Handshake,
    Mail,
    Link,
    Star,
    Tag,
    Users,
    Shell,
    ArrowBigUpDash,
    CalendarSync,
    Download,
    Play,
    GraduationCap,
    TrendingUp,
    Speech,
    MessageCircleCode,
    Heart,
    Lightbulb,
    Brain,
    HandHeart,
    MessagesSquare,
    NotebookPen,
    Hourglass,
    CalendarDays,
    GroupIcon,
    Laptop,
    LaptopMinimal,
    Check,
    BadgeHelpIcon,
    Bell,
    BellDotIcon,
  } from 'lucide-react';
  
  // Declare the icons object
  const icons = {
    BadgeHelp: <BadgeHelp  />,
    CircleHelp: <CircleHelp  />,
    Award: <Award  />,
    HeartHandshake: <HeartHandshake  />,
    Handshake: <Handshake  />,
    Mail: <Mail  />,
    Link: <Link  />,
    BadgeHelpIcon: <BadgeHelpIcon  />,
    Bell: <Bell  />,
    BellDotIcon: <BellDotIcon  />,
    GroupIcon: <GroupIcon  />,
    Laptop: <Laptop  />,
    LaptopMinimal: <LaptopMinimal  />,
    Check: <Check  />,
    Star: <Star  />,
    Tag: <Tag  />,
    Users: <Users  />,
    Shell: <Shell  />,
    ArrowBigUpDash: <ArrowBigUpDash  />,
    CalendarSync: <CalendarSync  />,
    Download: <Download  />,
    Play: <Play  />,
    GraduationCap: <GraduationCap  />,
    TrendingUp: <TrendingUp  />,
    Speech: <Speech  />,
    MessageCircleCode: <MessageCircleCode  />,
    Heart: <Heart  />,
    Lightbulb: <Lightbulb  />,
    Brain: <Brain  />,
    HandHeart: <HandHeart  />,
    MessagesSquare: <MessagesSquare  />,
    NotebookPen: <NotebookPen  />,
    Hourglass: <Hourglass  />,
    CalendarDays: <CalendarDays  />,
  };
  
  // Export the icons object as the default export
  export default icons;
  