import {
    BadgeHelp,
    CircleHelp,
    Award,
    HeartHandshake,
    Handshake,
    Mail,
    Link,
    Star,
    Tag,
    Users,
    Shell,
    ArrowBigUpDash,
    CalendarSync,
    Download,
    Play,
    GraduationCap,
    TrendingUp,
    Speech,
    MessageCircleCode,
    Heart,
    Lightbulb,
    Brain,
    HandHeart,
    MessagesSquare,
    NotebookPen,
    Hourglass,
    CalendarDays,
    GroupIcon,
    Laptop,
    LaptopMinimal,
    Check,
    BadgeHelpIcon,
    Bell,
    BellDotIcon,
  } from 'lucide-react';
  
  // Declare the icons object
  const icons = {
    BadgeHelp: <BadgeHelp className="inline-block text-black w-6 h-6" />,
    CircleHelp: <CircleHelp className="inline-block w-6 h-6 text-black" />,
    Award: <Award className="inline-block w-6 h-6 text-black" />,
    HeartHandshake: <HeartHandshake className="inline-block w-6 h-6" />,
    Handshake: <Handshake className="inline-block w-6 h-6" />,
    Mail: <Mail className="inline-block w-6 h-6" />,
    Link: <Link className="inline-block w-6 h-6" />,
    BadgeHelpIcon: <BadgeHelpIcon className="inline-block w-6 h-6" />,
    Bell: <Bell className="inline-block w-6 h-6" />,
    BellDotIcon: <BellDotIcon className="inline-block w-6 h-6" />,
    GroupIcon: <GroupIcon className="inline-block w-6 h-6" />,
    Laptop: <Laptop className="inline-block w-6 h-6" />,
    LaptopMinimal: <LaptopMinimal className="inline-block w-6 h-6" />,
    Check: <Check className="inline-block w-6 h-6" />,
    Star: <Star className="inline-block w-6 h-6" />,
    Tag: <Tag className="inline-block w-6 h-6" />,
    Users: <Users className="inline-block w-6 h-6" />,
    Shell: <Shell className="inline-block w-6 h-6" />,
    ArrowBigUpDash: <ArrowBigUpDash className="inline-block w-6 h-6" />,
    CalendarSync: <CalendarSync className="inline-block w-6 h-6" />,
    Download: <Download className="inline-block w-6 h-6" />,
    Play: <Play className="inline-block w-6 h-6" />,
    GraduationCap: <GraduationCap className="inline-block w-6 h-6" />,
    TrendingUp: <TrendingUp className="inline-block w-6 h-6" />,
    Speech: <Speech className="inline-block w-6 h-6" />,
    MessageCircleCode: <MessageCircleCode className="inline-block w-6 h-6" />,
    Heart: <Heart className="inline-block w-6 h-6" />,
    Lightbulb: <Lightbulb className="inline-block w-6 h-6" />,
    Brain: <Brain className="inline-block w-6 h-6" />,
    HandHeart: <HandHeart className="inline-block w-6 h-6" />,
    MessagesSquare: <MessagesSquare className="inline-block w-6 h-6" />,
    NotebookPen: <NotebookPen className="inline-block w-6 h-6" />,
    Hourglass: <Hourglass className="inline-block w-6 h-6" />,
    CalendarDays: <CalendarDays className="inline-block w-6 h-6" />,
  };
  
  // Export the icons object as the default export
  export default icons;
  