import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
// import Navbarr from "@/components/Navbar";
import Footer from "@/components/footer/Footer";
import Navbarr from "@/components/Navbar";
import Header from "@/components/Navbar/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className=" h-screen flex flex-col">
            {/* <Navbar /> */}
            <Header/>
            <div className="flex-grow">
              {children}
            </div>
            <Footer/>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
