import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import Footer from "@/components/footer/Footer";
import Header from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Modern Mannerisim",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  console.log(session);
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          <div className="flex flex-col">
            <Header />
            <div className="flex-grow">
              {children}
              <Toaster />
            </div>
            <Footer />
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
