import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { auth } from "@/auth";
import Footer from "@/components/footer/Footer";
import Header from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import Script from "next/script";
import { NotificationProvider } from "@/components/NotificationProvider";
import Script from "next/script";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Modern Mannerism",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>

      <html lang="en">
        <Script
          id="clarity-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i+"?ref=bwt";
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "q24bu9sz4y");`,
          }}
        />
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >

          <div className="flex flex-col">
            <Header />
            <div className="flex-grow">
              {children}
              <Toaster />
              <NotificationProvider />
            </div>
            <Footer />
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
